config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 
  resources :languages
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Timestamps
  # include Mongoid::Paranoia

  include CommonMeta

  after_save :clear_cache

  def clear_cache
    $redis.del "categories"
  end
end

app/models/concerns/common_meta.rb
module CommonMeta
  extend ActiveSupport::Concern
  included do
    field :name, :type => String
    field :desc, :type => String
    field :page_title, :type => String
  end
end

app/models/language.rb
class Language
  include Mongoid::Document
  include Mongoid::Timestamps
	# include Mongoid::Paranoia


  include CommonMeta

  after_save :clear_cache

  def clear_cache
    $redis.del "languages"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	include CategoriesHelper
	
	def index
		fetch_categories
	end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
	include LanguagesHelper

	def index
		fetch_languages
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
	def fetch_categories
    categories =  $redis.get("categories")
    if categories.nil?
      categories = Category.all.to_json
      $redis.set("categories", categories)
      # Expire the cache, every 3 hours
      $redis.expire("categories",3.hour.to_i)
    end
    @categories = JSON.load categories
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
	def fetch_languages
    languages =  $redis.get("languages")
    if languages.nil?
      languages = Language.all.to_json
      $redis.set("languages", languages)
      # Expire the cache, every 3 hours
      $redis.expire("languages",3.hour.to_i)
    end
    @languages = JSON.load languages
  end
end

app/views/categories/index.html.haml
%div.row
  %div.container  
    %h1
      Category Listing
    %table#categories.table.table-bordered.table-hover.table-striped
      %thead
        %tr
          %th 标题
          %th 描述
      %tbody
        - @categories.each do |cat|
          %tr
            %td
              = cat["name"]
            %td
              = cat["desc"]

app/views/languages/index.html.haml
%div.row
  %div.container
    %h1
      Language Listing
    %table.table.table-bordered.table-striped.table-hover
      %thead
        %tr
          %th 标题
          %th 内容
      %tbody
        - @languages.each do |lang|
          %tr
            %td
              = lang["name"]
            %td
              = lang["desc"]

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse{role: "navigation"}
  .container-fluid
    .navbar-header
      %a.navbar-brand Welcome
    %div
      %ul.nav.navbar-nav
        %li{ :class => ("active" if params[:controller] == "languages")}
          = link_to 'Language', languages_url
        %li{ :class => ("active" if params[:controller] == "categories")}
          = link_to 'Category', categories_url

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RedisDemo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

  %body
    = render :partial => "layouts/header"
    = yield